create table if not exists course.shopping_lists (
  id bigint generated by default as identity primary key,
  name text not null,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists shopping_lists_archived_at_idx
  on course.shopping_lists (archived_at desc);

create index if not exists shopping_lists_created_at_idx
  on course.shopping_lists (created_at desc);

create table if not exists course.shopping_list_items (
  shopping_list_id bigint not null references course.shopping_lists(id) on delete cascade,
  product_id bigint not null references course.products(id) on delete restrict,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (shopping_list_id, product_id)
);

create index if not exists shopping_list_items_list_position_idx
  on course.shopping_list_items (shopping_list_id, position);

create or replace function public.save_shopping_list(
  p_name text,
  p_product_ids bigint[]
)
returns bigint
language plpgsql
as $$
declare
  v_list_id bigint;
begin
  update course.shopping_lists
  set archived_at = now(),
      updated_at = now()
  where archived_at is null;

  insert into course.shopping_lists (name, archived_at)
  values (
    coalesce(nullif(trim(p_name), ''), 'Ma future course'),
    null
  )
  returning id into v_list_id;

  insert into course.shopping_list_items (shopping_list_id, product_id, position)
  select
    v_list_id,
    item.product_id,
    item.ord::integer
  from unnest(p_product_ids) with ordinality as item(product_id, ord);

  return v_list_id;
end;
$$;

create or replace view public.products as
select id, name, brand, product_url, photo_url, ean, created_at, updated_at, weight_grams
from course.products;

create or replace view public.product_prices as
select id, product_id, price, price_per_kg, currency, valid_from, valid_to, created_at
from course.product_prices;

create or replace view public.shopping_lists as
select id, name, archived_at, created_at, updated_at
from course.shopping_lists;

create or replace view public.shopping_list_items as
select shopping_list_id, product_id, position, created_at
from course.shopping_list_items;
